In [13]:
%reload_ext autoreload
%autoreload 2

import sys
import os
from pathlib import Path
import json_tricks

path = Path('.').resolve()

index = str(path).find('.laborantum')

if index > 0:
    path = str(path)[:index]

os.chdir(path)

path = Path(".laborantum/texts/Homeworks/3. Matrices/15. Sparse Matrix Product")

debug_cases = json_tricks.load(
    str(path / 'testcases' / 'debug_cases.json'))
public_cases = json_tricks.load(
    str(path / 'testcases' / 'public_cases.json'))

In [14]:
import numpy as np

def sparseProduct(A, B):
    print(B)
    return 0

In [15]:
import time

start = time.time()

debug_result = [sparseProduct(**x) for x in debug_cases]
answer = [sparseProduct(**x) for x in public_cases]

print(answer)

print(time.time() - start, '<- Elapsed time')

[[ 6  1  3]
 [ 6  2 -5]
 [ 4  3  4]
 [ 5  4 -3]
 [ 3  5  1]
 [ 1  3 -2]
 [ 0  3  3]
 [ 5  4 -3]]
[[7 2 2]]
[[ 0  2  0]
 [ 1  1  1]
 [ 2  0 -2]
 [ 0  2  1]
 [ 1  0  2]]
[[ 3  2  2]
 [ 2  3  1]
 [ 3  8 -4]]
[[ 2  3 -2]]
[[ 4  3 -2]
 [ 6  0 -5]]
[[ 0  0  2]
 [ 0  0 -1]
 [ 0  0 -5]
 [ 0  0  1]
 [ 0  0 -1]
 [ 0  0  0]]
[[ 0  0 -1]
 [ 0  2  1]
 [ 1  1  4]
 [ 0  1  4]
 [ 0  2  0]]
[[ 7  6 -3]
 [ 0  3 -5]
 [ 7  2 -5]
 [ 7  3 -3]]
[[ 0  2 -1]
 [ 0  2 -3]
 [ 2  0  1]
 [ 1  1 -4]
 [ 1  2  3]]
[[ 0  1 -3]
 [ 0  0  0]
 [ 1  0  1]
 [ 0  0  4]
 [ 1  1  4]]
[[ 0  2 -1]
 [ 3  1 -2]
 [ 2  3 -3]
 [ 0  3 -3]
 [ 1  0 -2]
 [ 1  3  3]
 [ 3  0 -4]
 [ 2  0  3]
 [ 1  0 -5]]
[[ 3  7 -3]
 [ 5  6  0]
 [ 0  0 -4]
 [ 3  4 -3]
 [ 7  4 -1]]
[[ 3  1 -3]
 [ 1  1 -4]]
[[ 3  3  0]
 [ 2  2 -1]
 [ 4  1  0]
 [ 1  2 -5]
 [ 4  4 -1]
 [ 3  1  3]]
[[ 2  3 -1]
 [ 1  1  0]
 [ 3  3 -1]
 [ 3  2  0]
 [ 0  0  0]
 [ 3  1  1]
 [ 1  2 -2]
 [ 2  0  2]
 [ 0  0  1]]
[[ 2  1 -5]
 [ 4  3  0]
 [ 5  1 -4]
 [ 3  2  2]
 [ 0  3  4]
 [ 3  0 -1]
 [ 